### ISSUE TITLE
Support codec 7?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/cram-js#1]
In the CRAM spec this is identified as `SUBEXP 7 int offset, int K subexponential coding`

The 1000 genomes cram files on their servers use this codec

This data directory has some files that access the 1000 genomes server. Note that it doesn't contain a refseq track so I am not sure if that is a factor

[1000genomes.tar.gz](https://github.com/GMOD/cram-js/files/2233134/1000genomes.tar.gz)

**Comment by rbuels** [comment]
It also uses gamma, ID 9. Wonder what pipeline produced these.

**Comment by rbuels** [comment]
fixed in master, will release soon in v1.3.0
