### ISSUE TITLE
Ensure compatibility with CRAM 3.1 files

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/cram-js#141]
samtools announced that their current version is the last version that will only output CRAM 3.0, next versions will be CRAM 3.1. We should test that we can accomodate 3.1 files

See "This is the last SAMtools / HTSlib release where CRAM 3.0 will be the default CRAM version. From the next we will change to CRAM 3.1 unless the version is explicitly specified, for example using samtools view -O cram,version=3.0."  https://github.com/samtools/samtools/releases/tag/1.21

**Comment by cmdcolin** [comment]
initial testing found at least one possible fail, possible patch with htscodecs PR here https://github.com/jkbonfield/htscodecs/pull/1

**Comment by cmdcolin** [comment]
cc @jrobinso there was a fix for some CRAM 3.1 files in new cram-js release v3.0.7. 

at least one file from the hts-specs test ("level4.cram") was failing in previous cram-js versions (https://github.com/samtools/hts-specs/tree/master/test/cram/3.1/passed)

i wanted to make sure cram 3.1 was supported since samtools release docs said they're making it on by default soon "https://github.com/samtools/samtools/releases"

**Comment by cmdcolin** [comment]
fixed by this PR https://github.com/GMOD/cram-js/pull/144

**Comment by jrobinso** [comment]
Thanks for the heads up!
