### ISSUE TITLE
Browser File support?

### ISSUE THREAD

**Issue by jrobinso** [GMOD/cram-js#21]
Thoughts on supporting the browser File object?  If you're not working on it, I might take a crack at it.   It should be pretty simple, I think we need to implement an "io" file class for it, then some conditional logic to prevent the app from blowing up if run in node.

**Comment by rbuels** [comment]
That would be great, perhaps a PR with a io/browserFile.js?

**Comment by jrobinso** [comment]
@rbuels That was my plan, but @cmdcolin pointed to using the fileHandle option and supplying an implementation from outside.  That might make more sense, and leaving cram-js a pure node application.

**Comment by jrobinso** [comment]
@rbuels @cmdcolin Perhaps we could put an implementation of filehandle (for args.filehandel) for the browser File object as an example file somewhere for other people to copy and use.    This keeps cram-js pure node.    When I have one I'll let you know.
