### ISSUE TITLE
Found in the wild: BAI index for CRAM masquarading as CRAI

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/cram-js#57]
Found this file https://s3.amazonaws.com/jbrowse.org/genomes/hg19/hg002/HG002_ONTrel2_16x_RG_HP10xtrioRTG.cram.crai

It is actually a BAI file....even though it has crai extension

I have read that BAI can actually serve as a CRAI index, so we could consider supporting this, or perhaps consider throwing an error in this case? 

Source:
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/

Apparently this is probably a GATK-ism  https://sourceforge.net/p/samtools/mailman/message/34369364/

**Comment by cmdcolin** [comment]
Note that samtools can handle this just with `samtools view https://s3.amazonaws.com/jbrowse.org/genomes/hg19/hg002/HG002_ONTrel2_16x_RG_HP10xtrioRTG.cram`

**Comment by rbuels** [comment]
Oh man that’s crazy. Not out of the question to support it but not until
somebody asks for it I think.

**Comment by cmdcolin** [comment]
Sounds reasonable

Section in the spec is "12 Indexing" under "BAM indexing" http://samtools.github.io/hts-specs/CRAMv3.pdf

There is a small vestigial reference to this in the tests as "test/data/hg19mini\#cram_with_bai_index.cram" but this may come from somewhere else and it does not use that bai index, just dump the contents of the CRAM

**Comment by cmdcolin** [comment]
Also have #58 for a slightly better error in this case

**Comment by cmdcolin** [comment]
Apparently, the so-called CRAM file is actually a BAM file in this directory, so the CRAM=BAM and the CRAI=BAI..
