### ISSUE TITLE
Estimate template length for more reads?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/cram-js#6]
I was wondering if it was possible to estimate template length for reads in more cases.

The current code seems to estimate smaller template lengths well but seems to struggle a bit on larger size ones

Example cram data attached with a test.js script that outputs the templateLength. Many are undefined except for shorter ones

[large_inserts_data.tar.gz](https://github.com/GMOD/cram-js/files/2548903/large_inserts_data.tar.gz)

Samtools view on the cram file with cut -f9 will be the template length too for comparison

**Comment by cmdcolin** [comment]
Actually I think from reading a bit further that the templateSize is used instead of templateLength for longer insert sizes. I don't know if those should be unified or perhaps it is worth keeping them separate as a distinction

**Comment by rbuels** [comment]
As a first guess I'd say on the parsing end, in cram-js, we should keep
them separate and not make too many judgments about what to use.

But on the JBrowse side, that is where we would make those judgments.

**Comment by cmdcolin** [comment]
It is not an exact match to samtools view TLEN values but seems basically reasonable to use "templateLength||templateSize"

**Comment by cmdcolin** [comment]
In any case this will be done jbrowse-side-of-things

**Comment by jrobinso** [comment]
Hi, I realize this is closed, but when computing the equivalent of SAM "TLEN" the convention is that the left-most mate should have a + sign, and rightmost -.     Currently, both mates have a + sign for "templateLength".
