### ISSUE TITLE
Push commit and tag for 1.5.6

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/cram-js#77]
The current commit for 1.5.6 and the github tag were not pushed during last release

We probably should fix our publish because this happens across all our packages

**Comment by cmdcolin** [comment]
I found over at @gmod/bam that this can be fixed by changing postpublish to postversion. random reference clue i found for it https://github.com/yarnpkg/yarn/issues/5243#issuecomment-438866490

**Comment by rbuels** [comment]
hmm ok I'll change it to postversion and see how that behaves.  i pushed
the 1.5.6 tag just now
