### ISSUE TITLE
Compiling for browser with Webpack or Browserify doesn't work.

### ISSUE THREAD

**Issue by tinyboxio** [GMOD/cram-js#87]
I've tried to export your CRAM and VCF modules with these tools with no luck. I've been able to browserify another VCF module, but I need your CRAM module to be used locally in the browser.

Have you tried this and do you know if this is possible? Thanks.

**Comment by cmdcolin** [comment]
It should be possible to use with webpack. I made a short demo showing how you may use @gmod/cram in a create-react-app context https://github.com/cmdcolin/gmodcram_demo

In create-react-app it doesn't show you the webpack configs, but if you have any info about your particular webpack setup maybe we can help

**Comment by cmdcolin** [comment]
The main point of the repo is just this file https://github.com/cmdcolin/gmodcram_demo/blob/master/src/App.js it shows a simple usage of @gmod/cram along with RemoteFile from generic-filehandle to download read info from a URL

**Comment by cmdcolin** [comment]
It may also be possible to use with browserify, though I haven't tried.

Further, there is a "simplified bundle" that is distributed called cram-bundle.js

If install @gmod/cram with npm you will see node_modules/@gmod/cram/cram-bundle.js

It is sort of undocumented but it could possibly avoid compilation issues. It creates a window.gmodCRAM variable in the browser with the functions and classes you might need.

 I'd personally try to get your webpack setup right but using cram-bundle.js could be a fallback

**Comment by tinyboxio** [comment]
I was able to get it to work with the cram-bundle.js. But is it possible to do requests for specified chromosomes and positions like you can do with samtools?

Thanks again!

**Comment by cmdcolin** [comment]
The getRecordsForRange uses a "sequence ID" which corresponds to the index in the header for the SQ lines....it is kind of tedious but you can parse the SQ lines, and then that creates a mapping of refName -> sequence ID

See code like this to create the mapping of refNameToId

From jbrowse code:

```
    const samHeader = await indexedCram.cram.getSamHeader()

      // use the @SQ lines in the header to figure out the
      // mapping between ref ref ID numbers and names
      const idToName: string[] = []
      const nameToId: Record<string, number> = {}
      const sqLines = samHeader.filter((l: { tag: string }) => l.tag === 'SQ')
      sqLines.forEach((sqLine: { data: HeaderLine[] }, refId: number) => {
        sqLine.data.forEach((item: HeaderLine) => {
          if (item.tag === 'SN') {
            // this is the ref name
            const refName = item.value
            nameToId[refName] = refId
            idToName[refId] = refName
          }
        })
      })

```

Then plug in

this.cram.getRecordsForRange(refNameToId['chr1'], 0, 100)

That will fetch chr1:1-100 in samtools (this tool accepts 0 based coordinates while samtools is 1 based



We could probably make a helper function for this that does the refNameToId mapping automatically but when the library was created it wasn't clear if all CRAM files had a sam header info like this

**Comment by tinyboxio** [comment]
FYI: Using webpack@4.44.2 did the trick. Webpack 5 gets messy with the config file. And even after configured right, the browser would give a Object.prototype is not defined error.

If anyone else reads this, I'd say just save the headache and install Webpack 4 until there is a solution or config that works.

**Comment by cmdcolin** [comment]
Ah interesting. we haven't used webpack@5 with our team....would be interested to know what could be done to make it work but webpack@5 was a pretty big change...they don't include some polyfills that webpack 4 provides by default for example. not sure if that is the reason but could be a factor

**Comment by tinyboxio** [comment]
Hopefully last question. Can I use Webpack to make IndexedFasta work in the browser with the browser file input?

I used Webpack for @gmod/indexedfasta but it seems to use Node's readFile? After a quick look through the code, it looks like remote fasta files/indexes aren't supported as well?

**Comment by cmdcolin** [comment]
@tinyboxio we tried to "standardize" on a "File type abstraction" over remote files (RemoteFile), browser file inputs (BlobFile), and nodejs filesystem operations (LocalFile) in https://github.com/GMOD/generic-filehandle

So all our modules like @gmod/indexedfasta, @gmod/cram, @gmod/bam, etc can accept generic-filehandle type things

You can alternatively implement your own class that is like a generic-filehandle type, but you can use BlobFile in the case of something read from a `<input type="file"/>`

**Comment by cmdcolin** [comment]
We actually haven't gotten around to using BlobFile in jbrowse 2 yet so it hasn't been tested much in production, but hopefully it will work for you, and that is the basic idea behind the "filehandles" :)

**Comment by tinyboxio** [comment]
Yeah, unless I'm doing something totally wrong, it doesn't look like IndexedFasta handles browser input files[] correctly.

I was able to modify the code so a local IndexedFasta object was able to be created, but then more errors are generated when it tried to resolve the path of the file.

**Comment by cmdcolin** [comment]
do you have any small example code that shows the issue?

**Comment by cmdcolin** [comment]
feel free to upload code sandbox or a small repo like create-react-app i.e. https://github.com/cmdcolin/gmodcram_demo/blob/master/src/App.js

**Comment by cmdcolin** [comment]
note that you would likely want to use something like this

```
const t = new IndexedFasta({
  filehandle: new BlobFile(blobFromFileInput),
  faiFilehandle: new BlobFile(blobFromFileInputFAI)
});
```

**Comment by tinyboxio** [comment]
I appreciate your help. Looks like it was user error after all.

I ended up using fasta, fai, and gzi to get the local (browser) blob to work. I was previous using incorrect filehandles, but it's a bit humorous that I still got it to (partially) work by modifying a few lines of code in the module.

Initially, I couldn't figure out why it was loading everything into memory as well, but then realized the fasta was gzip compressed instead of bgzip. This simple problem was a huge headache even though it was such a simple problem that should have been obvious. 🤦‍♂️

Along with user error, I feel that there is currently a steep learning curve for working with CRAM/FASTA, but the documentation also isn't as straightforward as a VCF module I've been using (which has been a breeze to work with). I find myself looking at your module code in confusion to figure out what to do. Not that I expect all of your focus to be on documentation because you are obviously building that awesome JBrowse application. And your modules are perhaps more robust even if they are currently not as intuitive to use.

I gotta take a break from this CRAM module/bundle for a while. But I'll probably create a repo soon since I have a few promise errors in the console, and I don't know why they are occuring.

Thank you so much for your help!

**Comment by tinyboxio** [comment]
Also, for seqFetch, I had to use chromosome names instead of integers. That one took a while to figure out.

**Comment by cmdcolin** [comment]
for what it's worth, great to see you got it working thus far! probably it would be good to make a dedicated section to the guide about these "seq ids" vs the seq name...or make our API able to use seqNames directly...

**Comment by cmdcolin** [comment]
i think this issue can probably be closed for now. seqNames issue will be done via docs or API changes internally
